using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using Jakojaannos.GodotSourceGenerator;

[Generator]
public class ConfigWarningSourceGenerator : ISourceGenerator {
    public void Execute(GeneratorExecutionContext context) {
        var treesWithClassesWithProperties =
            context
                .Compilation
                .SyntaxTrees
                .Where(syntaxTree =>
                    syntaxTree
                        .GetRoot()
                        // The tree contains a class declaration node
                        .DescendantNodes()
                        .OfType<ClassDeclarationSyntax>()
                        .Any(declaredClass => declaredClass
                            .DescendantNodes()
                            // The class declaration contains attributes
                            .OfType<AttributeSyntax>()
                            .Any()
                        )
                );

        var configWarningAttributeSymbol = context.Compilation.GetTypeByMetadataName(typeof(ConfigWarningAttribute).FullName!)!;

        foreach (var tree in treesWithClassesWithProperties) {
            var declaredClasses = tree
                .GetRoot()
                .DescendantNodes()
                .OfType<ClassDeclarationSyntax>()
                .Where(declaredClass => declaredClass
                    .DescendantNodes()
                    .OfType<AttributeSyntax>()
                    .Any()
                );
            var semanticModel = context.Compilation.GetSemanticModel(tree) ?? throw new InvalidOperationException();

            foreach (var declaredClass in declaredClasses) {
                var nodes = declaredClass
                        .DescendantNodes()
                        .OfType<AttributeSyntax>()
                        .FirstOrDefault(a => a.DescendantTokens().Any(token => token.IsKind(SyntaxKind.IdentifierToken) && semanticModel.GetTypeInfo(token.Parent!).Type?.Name == "GlobalClassAttribute"))
                        ?.DescendantTokens()
                        ?.Where(token => token.IsKind(SyntaxKind.IdentifierToken))
                        ?.ToList();

                if (nodes is null) {
                    continue;
                }

                var className = declaredClass.Identifier.ToString();
                var relatedClass = semanticModel.GetDeclaredSymbol(declaredClass);

                string generatedProperties = "";
                foreach (var classProperty in declaredClass.Members.Where(m => m.IsKind(SyntaxKind.PropertyDeclaration)).OfType<PropertyDeclarationSyntax>()) {
                    var isConfigWarning = classProperty.DescendantTokens().Any(token => token.IsKind(SyntaxKind.IdentifierToken) && semanticModel.GetTypeInfo(token.Parent!).Type?.Name == configWarningAttributeSymbol.Name);
                    if (!isConfigWarning) {
                        continue;
                    }

                    var propertyName = classProperty.Identifier.ToString();
                    var propertyType = semanticModel.GetTypeInfo(classProperty.Type).Type!.Name;

                    generatedProperties += GeneratedProperty(propertyType, propertyName);
                }

                if (generatedProperties.Trim().Length > 0) {
                    string source = GenerateClass(relatedClass!, generatedProperties);
                    context.AddSource($"{className}.generated.cs", source);
                }
            }
        }
    }

    private static string GenerateClass(INamedTypeSymbol clazz, string generatedProperties) {

        var className = clazz.Name;
        var classNamespace = clazz.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"namespace {clazz.ContainingNamespace};";

        var baseNamespace = clazz.BaseType!.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"{clazz.BaseType!.ContainingNamespace}.";
        var classBase = baseNamespace + clazz.BaseType.Name;

        return $@"// <auto-generated/>
#nullable enable
using Godot;
using System;
using System.Reflection;
using System.Linq;

using Jakojaannos.GodotSourceGenerator;

{classNamespace}

public partial class {className} : {classBase} {{
    {generatedProperties}

    public override partial string[] _GetConfigurationWarnings() {{
        return (base._GetConfigurationWarnings() ?? [])
            .Union(this
                .GetType()
                .GetProperties()
                .Where(f => f.GetCustomAttribute<ExportAttribute>() is not null)
                .Where(f => f.GetCustomAttribute<ConfigWarningAttribute>() is not null)
                .Where(field => field.GetValue(this) is null)
                .Select(field => $""{{field.Name}} is required but not set!"")
            )
            .ToArray();
    }}
}}
#nullable disable
";
    }

    private static string GeneratedProperty(string propertyType, string propertyName) {
        return $@"
    public partial {propertyType} {propertyName} {{
        get => Engine.IsEditorHint() ? _{propertyName}! : throw new InvalidOperationException(""Required field '${propertyName}' is not set!"");
        set {{ _{propertyName} = value; UpdateConfigurationWarnings(); }}
    }}
    private {propertyType}? _{propertyName};
";
    }

    public void Initialize(GeneratorInitializationContext context) {
        // No initialization required for this one
    }
}
