using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using Jakojaannos.GodotSourceGenerator;

[Generator]
public class ConfigWarningSourceGenerator : ISourceGenerator {
    public void Execute(GeneratorExecutionContext context) {
        var treesWithClassesWithProperties =
            context
                .Compilation
                .SyntaxTrees
                .Where(syntaxTree =>
                    syntaxTree
                        .GetRoot()
                        // The tree contains a class declaration node
                        .DescendantNodes()
                        .OfType<ClassDeclarationSyntax>()
                        .Any(declaredClass => declaredClass
                            .DescendantNodes()
                            // The class declaration contains attributes
                            .OfType<AttributeSyntax>()
                            .Any()
                        )
                );

        var configWarningAttributeSymbol = context.Compilation.GetTypeByMetadataName(typeof(ConfigWarningAttribute).FullName!)!;

        foreach (var tree in treesWithClassesWithProperties) {
            var declaredClasses = tree
                .GetRoot()
                .DescendantNodes()
                .OfType<ClassDeclarationSyntax>()
                .Where(declaredClass => declaredClass
                    .DescendantNodes()
                    .OfType<AttributeSyntax>()
                    .Any()
                );
            var semanticModel = context.Compilation.GetSemanticModel(tree) ?? throw new InvalidOperationException();

            foreach (var declaredClass in declaredClasses) {
                var nodes = declaredClass
                        .DescendantNodes()
                        .OfType<AttributeSyntax>()
                        .FirstOrDefault(a => a.DescendantTokens().Any(token => token.IsKind(SyntaxKind.IdentifierToken) && semanticModel.GetTypeInfo(token.Parent!).Type?.Name == "GlobalClassAttribute"))
                        ?.DescendantTokens()
                        ?.Where(token => token.IsKind(SyntaxKind.IdentifierToken))
                        ?.ToList();

                if (nodes is null) {
                    continue;
                }

                var className = declaredClass.Identifier.ToString();
                var relatedClass = semanticModel.GetDeclaredSymbol(declaredClass);

                string generatedProperties = "";
                foreach (var classProperty in declaredClass.Members.Where(m => m.IsKind(SyntaxKind.FieldDeclaration)).OfType<FieldDeclarationSyntax>()) {
                    var isConfigWarning = classProperty.DescendantTokens().Any(token => token.IsKind(SyntaxKind.IdentifierToken) && semanticModel.GetTypeInfo(token.Parent!).Type?.Name == configWarningAttributeSymbol.Name);
                    if (!isConfigWarning) {
                        continue;
                    }

                    var fieldType = semanticModel.GetTypeInfo(classProperty.Declaration.Type).Type!.Name;
                    foreach (var variable in classProperty.Declaration.Variables) {
                        var fieldName = variable.Identifier.ToString();
                        generatedProperties += GeneratedProperty(fieldType, fieldName);
                    }
                }

                if (generatedProperties.Trim().Length > 0) {
                    string source = GenerateClass(relatedClass!, generatedProperties);
                    context.AddSource($"{className}.generated.cs", source);
                }
            }
        }
    }

    private static string GenerateClass(INamedTypeSymbol clazz, string generatedProperties) {

        var className = clazz.Name;
        var classNamespace = clazz.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"namespace {clazz.ContainingNamespace};";

        var baseNamespace = clazz.BaseType!.ContainingNamespace.IsGlobalNamespace
            ? ""
            : $"{clazz.BaseType!.ContainingNamespace}.";
        var classBase = baseNamespace + clazz.BaseType.Name;

        return $@"// <auto-generated/>
#nullable enable
using Godot;
using System;
using System.Reflection;
using System.Linq;

using Jakojaannos.GodotSourceGenerator;

{classNamespace}

public partial class {className} : {classBase} {{
    {generatedProperties}

    public override partial string[] _GetConfigurationWarnings() {{
        return (base._GetConfigurationWarnings() ?? [])
            .Union(this
                .GetType()
                .GetProperties()
                .Where(f => f.GetCustomAttribute<ExportAttribute>() is not null)
                .Where(f => f.GetCustomAttribute<ConfigWarningAttribute>() is not null)
                .Where(field => field.GetValue(this) is null)
                .Select(field => $""{{field.Name}} is required but not set!"")
            )
            .ToArray();
    }}
}}
#nullable disable
";
    }

    private static string GeneratedProperty(string propertyType, string backingFieldName) {
        var propertyName = backingFieldName.TrimStart(['_']) switch {
            null => throw new InvalidOperationException("Field name can't be null"),
            "" => throw new InvalidOperationException("Field name can't be empty"),
            var name => name[0].ToString().ToUpper() + name.Substring(1),
        };

        return $@"
    public {propertyType} {propertyName} {{
        get {{
            if (Engine.IsEditorHint()) {{
                if ({backingFieldName} is Node node && node.IsQueuedForDeletion()) {{
                    {backingFieldName} = null;
                }}
                return {backingFieldName}!;
            }}

            if ({backingFieldName} is null) {{
                throw new InvalidOperationException($""Required field '{propertyName}' is not set on '{{Name}}'!"");
            }}

            return {backingFieldName};
        }}
        set {{
            {backingFieldName} = value;
            UpdateConfigurationWarnings();
        }}
    }}
";
    }

    public void Initialize(GeneratorInitializationContext context) {
        // No initialization required for this one
    }
}
